<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class AnimalSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table("animals")->insert([
            [
                'aname' => 'Lajos',
                'species' => 'donkey',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'aname' => 'Csuri',
                'species' => 'sparrow',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'aname' => 'Böske',
                'species' => 'horse',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'aname' => 'Bark',
                'species' => 'fox',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'aname' => 'Csámpás',
                'species' => 'donkey',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'aname' => 'Csett',
                'species' => 'shrike',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'aname' => 'Kata',
                'species' => 'hen',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'aname' => 'Tanti',
                'species' => 'owl',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'aname' => 'Csimbók',
                'species' => 'dog',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'aname' => 'Pagát',
                'species' => 'dog',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'aname' => 'Szú',
                'species' => 'hedgehog',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'aname' => 'Őz Egon',
                'species' => 'deer',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'aname' => 'Vu',
                'species' => 'owl',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'aname' => 'Őzy Egon',
                'species' => 'deer',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'aname' => 'Szimba Msenzi',
                'species' => 'lion',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'aname' => 'Cin',
                'species' => 'mouse',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'aname' => 'Ri',
                'species' => 'swallow',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'aname' => 'Hóka',
                'species' => 'horse',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'aname' => 'Szi',
                'species' => 'snake',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'aname' => 'Kag',
                'species' => 'fox',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'aname' => 'Kurra',
                'species' => 'dog',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'aname' => 'Mú',
                'species' => 'cattle',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'aname' => 'Panna',
                'species' => 'fox',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'aname' => 'Bikfic',
                'species' => 'dog',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'aname' => 'Tücsök',
                'species' => 'dog',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'aname' => 'Uccu',
                'species' => 'dog',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'aname' => 'Killi',
                'species' => 'goshawk',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'aname' => 'Csetnik',
                'species' => 'dog',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'aname' => 'Elemér',
                'species' => 'horse',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'aname' => 'Duhaj',
                'species' => 'cattle',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'aname' => 'Mici',
                'species' => 'cat',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'aname' => 'Balambér',
                'species' => 'donkey',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'aname' => 'Csusz',
                'species' => 'lizard',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'aname' => 'Nyu',
                'species' => 'wolf',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'aname' => 'Náci',
                'species' => 'cat',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'aname' => 'Kalán',
                'species' => 'rabbit',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'aname' => 'Ede',
                'species' => 'bear',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'aname' => 'Kakat',
                'species' => 'pheasant',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'aname' => 'Ráró',
                'species' => 'eagle',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'aname' => 'fox Gyuri',
                'species' => 'fox',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'aname' => 'Dörmögő Dömötör',
                'species' => 'bear',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'aname' => 'Nyusziné Kalán Eleonóra',
                'species' => 'rabbit',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'aname' => 'Kocáriné Koca',
                'species' => 'wild boar',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'aname' => 'Ci-nyi',
                'species' => 'mouse',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'aname' => 'Fickó',
                'species' => 'dog',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'aname' => 'Matyi',
                'species' => 'jay',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'aname' => 'Lupi',
                'species' => 'dog',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'aname' => 'Professzor úr',
                'species' => 'owl',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'aname' => 'Bob',
                'species' => 'dog',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'aname' => 'Nerr',
                'species' => 'sparrowhawk',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'aname' => 'Csutak',
                'species' => 'dog',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'aname' => 'fox Elek',
                'species' => 'fox',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'aname' => 'Mátyás',
                'species' => 'jay',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'aname' => 'Tódor',
                'species' => 'lamb',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'aname' => 'Pipincs',
                'species' => 'monkey',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'aname' => 'Nagykigláb',
                'species' => 'stork',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'aname' => 'Kerecsen',
                'species' => 'falcon',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'aname' => 'Mackó',
                'species' => 'dog',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'aname' => 'Uhu',
                'species' => 'owl',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'aname' => 'Embrió',
                'species' => 'horse',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'aname' => 'Karr',
                'species' => 'falcon',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'aname' => 'Csibor',
                'species' => 'dog',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'aname' => 'Miska',
                'species' => 'horse',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'aname' => 'Pi',
                'species' => 'ground squirrel',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'aname' => 'Vuk',
                'species' => 'fox',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'aname' => 'Csuvik',
                'species' => 'owl',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'aname' => 'Bogáncs',
                'species' => 'dog',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'aname' => 'Fáni',
                'species' => 'cattle',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'aname' => 'Rigó',
                'species' => 'horse',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'aname' => 'Zsuzsi',
                'species' => 'donkey',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'aname' => 'Tala',
                'species' => 'vulture',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'aname' => 'Ruca',
                'species' => 'horse',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'aname' => 'Nyaú',
                'species' => 'cat',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'aname' => 'Kiri',
                'species' => 'kestrel',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'aname' => 'Ravasz',
                'species' => 'fox',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'aname' => 'Bubi',
                'species' => 'horse',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'aname' => 'Bee',
                'species' => 'lamb',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'aname' => 'Kiz',
                'species' => 'rat',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'aname' => 'Oszkár',
                'species' => 'crow',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'aname' => 'Miska',
                'species' => 'dog',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'aname' => 'Vé',
                'species' => 'stork',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'aname' => 'Rá',
                'species' => 'crow',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'aname' => 'Kanalas Ágoston',
                'species' => 'rabbit',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'aname' => 'Mérges',
                'species' => 'dog',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'aname' => 'Kiő',
                'species' => 'buzzard',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'aname' => 'Toró',
                'species' => 'crow',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'aname' => 'Szimba',
                'species' => 'lion',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'aname' => 'Gyuri',
                'species' => 'hen',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'aname' => 'Holhorse',
                'species' => 'horse',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'aname' => 'Bu',
                'species' => 'cattle',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'aname' => 'Dorottya',
                'species' => 'bear',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'aname' => 'Sári',
                'species' => 'horse',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'aname' => 'Marcsa',
                'species' => 'horse',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'aname' => 'Csuvik Aladár',
                'species' => 'owl',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'aname' => 'Vica',
                'species' => 'cattle',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'aname' => 'Juci',
                'species' => 'cat',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'aname' => 'Föcske',
                'species' => 'dog',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'aname' => 'Csirik',
                'species' => 'weasel',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'aname' => 'Vak Toportyán',
                'species' => 'wolf',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'aname' => 'János',
                'species' => 'crow',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'aname' => 'Káró',
                'species' => 'dog',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'aname' => 'Csele',
                'species' => 'fox',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'aname' => 'Kurri',
                'species' => 'hen',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'aname' => 'Szarka Ákos',
                'species' => 'magpie',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'aname' => 'Julcsa',
                'species' => 'cattle',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'aname' => 'Sárkány',
                'species' => 'horse',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'aname' => 'Kró',
                'species' => 'raven',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'aname' => 'ja Uleja',
                'species' => 'lion',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'aname' => 'Paták',
                'species' => 'horse',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'aname' => 'Bagó',
                'species' => 'dog',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'aname' => 'Íny',
                'species' => 'fox',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'aname' => 'Pici',
                'species' => 'dog',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'aname' => 'Fergeteg',
                'species' => 'horse',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'aname' => 'Csikasz',
                'species' => 'dog',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'aname' => 'Cse',
                'species' => 'swallow',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'aname' => 'Vörös',
                'species' => 'fox',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'aname' => 'Pepi',
                'species' => 'marten',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'aname' => 'Manci',
                'species' => 'horse',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'aname' => 'Dzsinn',
                'species' => 'leopard',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'aname' => 'Vit',
                'species' => 'swallow',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'aname' => 'Sármány',
                'species' => 'horse',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'aname' => 'Csákó',
                'species' => 'cattle',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'aname' => 'Citér',
                'species' => 'tit',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'aname' => 'Füstös',
                'species' => 'thrush',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'aname' => 'Kanalas Boriska',
                'species' => 'rabbit',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'aname' => 'Hú',
                'species' => 'owl',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'aname' => 'Csám',
                'species' => 'wild boar',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'aname' => 'Suó',
                'species' => 'falcon',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'aname' => 'Parpu',
                'species' => 'heron',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'aname' => 'Csufi',
                'species' => 'dog',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'aname' => 'Küllő',
                'species' => 'woodpecker',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'aname' => 'Tás',
                'species' => 'wild duck',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'aname' => 'Bruku',
                'species' => 'pigeon',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'aname' => 'Fecske',
                'species' => 'dog',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'aname' => 'Zu',
                'species' => 'fly',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'aname' => 'Borzas',
                'species' => 'dog',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'aname' => 'Szeles',
                'species' => 'horse',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'aname' => 'Mirci',
                'species' => 'cat',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'aname' => 'Csipet',
                'species' => 'dog',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'aname' => 'Sut',
                'species' => 'fox',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'aname' => 'Kele',
                'species' => 'stork',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'aname' => 'Harat',
                'species' => 'eagle',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'aname' => 'Vahúr',
                'species' => 'dog',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'aname' => 'Kati',
                'species' => 'horse',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'aname' => 'Treff',
                'species' => 'dog',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'aname' => 'Talpas',
                'species' => 'wolf',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'aname' => 'Mari',
                'species' => 'thrush',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'aname' => 'Sajó',
                'species' => 'dog',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'aname' => 'Csisz',
                'species' => 'bat',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'aname' => 'Unka',
                'species' => 'frog',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'aname' => 'Zsivány',
                'species' => 'cattle',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'aname' => 'Dáma',
                'species' => 'dog',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'aname' => 'Muki',
                'species' => 'marten',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'aname' => 'Peták',
                'species' => 'dog',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'aname' => 'Jakab',
                'species' => 'dog',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'aname' => 'Finánc',
                'species' => 'dog',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'aname' => 'Lutra',
                'species' => 'otter',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'aname' => 'Csillag',
                'species' => 'horse',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'aname' => 'Miska',
                'species' => 'donkey',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'aname' => 'Csilli',
                'species' => 'warbler',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'aname' => 'Szidike',
                'species' => 'dog',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'aname' => 'Ordas Csikasz',
                'species' => 'wolf',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'aname' => 'Betyár',
                'species' => 'dog',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'aname' => 'Brozovics Borz',
                'species' => 'badger',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'aname' => 'Pille',
                'species' => 'butterfly',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'aname' => 'Labanc',
                'species' => 'dog',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'aname' => 'Gege',
                'species' => 'wild goose',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'aname' => 'Morzsa',
                'species' => 'dog',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'aname' => 'Szarvas Menyhért',
                'species' => 'stag',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'aname' => 'Kanalas Gusztáv',
                'species' => 'rabbit',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'aname' => 'Szultán',
                'species' => 'lion',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'aname' => 'Tanár úr',
                'species' => 'owl',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'aname' => 'Kanalas Őrvezető',
                'species' => 'rabbit',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'aname' => 'Maros',
                'species' => 'dog',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'aname' => 'Kapitány',
                'species' => 'horse',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'aname' => 'Ravaszdi',
                'species' => 'fox',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'aname' => 'Tecs',
                'species' => 'magpie',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'aname' => 'Bába',
                'species' => 'stork',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'aname' => 'Bimbó',
                'species' => 'cattle',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'aname' => 'Hosszúláb',
                'species' => 'stork',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'aname' => 'Fokos',
                'species' => 'horse',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'aname' => 'Fészkes Annamária',
                'species' => 'hen',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'aname' => 'Uzsárdi Mihály',
                'species' => 'raven',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'aname' => 'Elemér',
                'species' => 'parrot',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'aname' => 'Bogár',
                'species' => 'horse',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'aname' => 'Ravaszdy Ravasz Elek',
                'species' => 'fox',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'aname' => 'Csí',
                'species' => 'swallow',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'aname' => 'Berci',
                'species' => 'dog',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'aname' => 'Nóra',
                'species' => 'dog',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'aname' => 'Szikra',
                'species' => 'dog',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'aname' => 'Basa',
                'species' => 'dog',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'aname' => 'Szellő',
                'species' => 'horse',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'aname' => 'Csalavér',
                'species' => 'fox',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'aname' => 'Teofil',
                'species' => 'donkey',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'aname' => 'Karak',
                'species' => 'fox',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'aname' => 'Bodri',
                'species' => 'dog',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'aname' => 'Muki',
                'species' => 'dog',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'aname' => 'Cilike',
                'species' => 'cat',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'aname' => 'Betyár',
                'species' => 'horse',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'aname' => 'Deres',
                'species' => 'horse',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
